"""Curated fallback dataset of Lausanne cultural events.

Used when live scraping yields no results, so the app remains functional
in offline / sandboxed environments (e.g. CI, Codespaces preview).
"""
from __future__ import annotations

FALLBACK_EVENTS: list[dict] = [
    {
        "id": "evt001",
        "title": "Concert Symphonique — Beethoven & Brahms",
        "date": "2026-05-02", "time": "20:00", "end_date": "",
        "location": "Opéra de Lausanne",
        "address": "Avenue du Théâtre 12, 1005 Lausanne",
        "category": "Musique", "subcategory": "Classique",
        "description": "L'Orchestre de Chambre de Lausanne vous invite à une soirée inoubliable avec les œuvres majeures de Beethoven et Brahms.",
        "image": "https://images.unsplash.com/photo-1507838153414-b4b713384a76?w=800&q=80",
        "price": "CHF 35–85", "url": "#",
        "tags": ["classique", "orchestre"], "featured": True,
    },
    {
        "id": "evt002",
        "title": "Hamlet — Théâtre de Vidy",
        "date": "2026-05-04", "time": "19:30", "end_date": "",
        "location": "Théâtre Vidy-Lausanne",
        "address": "Avenue E.-H. Jaques-Dalcroze 5, 1007 Lausanne",
        "category": "Théâtre", "subcategory": "Pièce",
        "description": "Une nouvelle mise en scène contemporaine du chef-d'œuvre de Shakespeare, revisitée par Christiane Jatahy.",
        "image": "https://images.unsplash.com/photo-1503095396549-807759245b35?w=800&q=80",
        "price": "CHF 18–42", "url": "#",
        "tags": ["shakespeare", "contemporain"], "featured": True,
    },
    {
        "id": "evt003",
        "title": "Exposition — Giacometti & ses contemporains",
        "date": "2026-04-15", "time": "10:00", "end_date": "2026-07-30",
        "location": "Fondation de l'Hermitage",
        "address": "Route du Signal 2, 1010 Lausanne",
        "category": "Exposition", "subcategory": "Beaux-Arts",
        "description": "Une rétrospective exceptionnelle mettant en lumière les échanges entre Alberto Giacometti et ses contemporains parisiens.",
        "image": "https://images.unsplash.com/photo-1578321272176-b7bbc0679853?w=800&q=80",
        "price": "CHF 20", "url": "#",
        "tags": ["giacometti", "sculpture"], "featured": True,
    },
    {
        "id": "evt004",
        "title": "Festival du Film de Lausanne",
        "date": "2026-05-08", "time": "18:00", "end_date": "2026-05-15",
        "location": "Cinéma Bourg",
        "address": "Place St-François 3, 1002 Lausanne",
        "category": "Cinéma", "subcategory": "Festival",
        "description": "La 14e édition présente une sélection de 50 films en compétition internationale, avec avant-premières et rencontres avec les réalisateurs.",
        "image": "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=800&q=80",
        "price": "CHF 15 / pass CHF 80", "url": "#",
        "tags": ["festival", "international"], "featured": True,
    },
    {
        "id": "evt005",
        "title": "Ballet — Le Lac des Cygnes",
        "date": "2026-05-10", "time": "20:00", "end_date": "",
        "location": "Opéra de Lausanne",
        "address": "Avenue du Théâtre 12, 1005 Lausanne",
        "category": "Danse", "subcategory": "Ballet",
        "description": "Le Ballet du Bolchoï présente sa version légendaire avec la musique de Tchaïkovski. Plus de 80 danseurs sur scène.",
        "image": "https://images.unsplash.com/photo-1518834107812-67b0b7c58434?w=800&q=80",
        "price": "CHF 45–120", "url": "#",
        "tags": ["ballet", "tchaïkovski"], "featured": False,
    },
    {
        "id": "evt006",
        "title": "Nuit des Musées Lausanne 2026",
        "date": "2026-05-16", "time": "18:00", "end_date": "2026-05-17",
        "location": "Toute la ville", "address": "Lausanne",
        "category": "Festival", "subcategory": "Culture",
        "description": "Une nuit où tous les musées de Lausanne ouvrent leurs portes gratuitement jusqu'à 2h du matin. 25 lieux, performances live, installations surprises.",
        "image": "https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=800&q=80",
        "price": "Gratuit", "url": "#",
        "tags": ["musées", "gratuit", "famille"], "featured": True,
    },
    {
        "id": "evt007",
        "title": "Jazz Sous Les Étoiles",
        "date": "2026-05-20", "time": "21:00", "end_date": "",
        "location": "Casino de Montbenon",
        "address": "Allée Ernest-Ansermet 3, 1003 Lausanne",
        "category": "Musique", "subcategory": "Jazz",
        "description": "Soirée jazz en plein air sur les terrasses panoramiques avec vue sur le Léman. Featuring Tigran Hamasyan Trio.",
        "image": "https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=800&q=80",
        "price": "CHF 28", "url": "#",
        "tags": ["jazz", "plein air", "léman"], "featured": False,
    },
    {
        "id": "evt008",
        "title": "Les Enfants du Paradis — Jeune Public",
        "date": "2026-05-22", "time": "15:00", "end_date": "",
        "location": "Théâtre de Beaulieu",
        "address": "Avenue des Bergières 10, 1004 Lausanne",
        "category": "Famille", "subcategory": "Théâtre jeunesse",
        "description": "Un spectacle enchanté pour les enfants de 4 à 10 ans. Marionnettes géantes, magie et musique.",
        "image": "https://images.unsplash.com/photo-1576267423445-b2e0074d68a4?w=800&q=80",
        "price": "CHF 12 / famille CHF 40", "url": "#",
        "tags": ["enfants", "marionnettes"], "featured": False,
    },
    {
        "id": "evt009",
        "title": "Conférence — L'IA et la Création Artistique",
        "date": "2026-05-25", "time": "19:00", "end_date": "",
        "location": "EPFL — Rolex Learning Center",
        "address": "Route Cantonale, 1015 Lausanne",
        "category": "Conférence", "subcategory": "Technologie",
        "description": "Réfléchissons à l'impact de l'IA sur la création artistique. Des intervenants de renom du monde de l'art, de la tech et de la philosophie.",
        "image": "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800&q=80",
        "price": "Gratuit sur inscription", "url": "#",
        "tags": ["ia", "art", "epfl"], "featured": False,
    },
    {
        "id": "evt010",
        "title": "Photo Elysée — Regards sur l'Afrique",
        "date": "2026-04-20", "time": "10:00", "end_date": "2026-08-15",
        "location": "Photo Elysée",
        "address": "Place de la Gare 17, 1003 Lausanne",
        "category": "Exposition", "subcategory": "Photographie",
        "description": "Exposition collective inédite rassemblant le travail de 15 photographes africains contemporains.",
        "image": "https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=800&q=80",
        "price": "CHF 16 / réduit CHF 10", "url": "#",
        "tags": ["photographie", "afrique"], "featured": False,
    },
    {
        "id": "evt011",
        "title": "Rock en Scène — Festival",
        "date": "2026-06-05", "time": "17:00", "end_date": "2026-06-07",
        "location": "Parc de Mon-Repos",
        "address": "Avenue Mon-Repos 4, 1005 Lausanne",
        "category": "Musique", "subcategory": "Rock",
        "description": "8e édition du festival rock de Lausanne. Phoenix, Parcels, Arab Strap et 20 autres artistes sur 3 scènes.",
        "image": "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800&q=80",
        "price": "CHF 45 / jour — CHF 110 / 3 jours", "url": "#",
        "tags": ["rock", "festival", "phoenix"], "featured": True,
    },
    {
        "id": "evt012",
        "title": "Atelier Céramique Contemporaine",
        "date": "2026-05-03", "time": "14:00", "end_date": "",
        "location": "Espace Culturel des Terreaux",
        "address": "Rue des Terreaux 12, 1002 Lausanne",
        "category": "Atelier", "subcategory": "Artisanat",
        "description": "Initiation à la céramique animée par la céramiste lausannoise Camille Roch. Session de 3h, tous niveaux.",
        "image": "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=800&q=80",
        "price": "CHF 55 (matériel inclus)", "url": "#",
        "tags": ["atelier", "céramique"], "featured": False,
    },
    {
        "id": "evt013",
        "title": "Vivaldi — Les Quatre Saisons",
        "date": "2026-05-12", "time": "20:00", "end_date": "",
        "location": "Cathédrale de Lausanne",
        "address": "Place de la Cathédrale, 1005 Lausanne",
        "category": "Musique", "subcategory": "Classique",
        "description": "Dans le cadre majestueux de la cathédrale gothique, une expérience acoustique unique avec I Musici de Montréal.",
        "image": "https://images.unsplash.com/photo-1519682337058-a94d519337bc?w=800&q=80",
        "price": "CHF 30–60", "url": "#",
        "tags": ["vivaldi", "baroque"], "featured": False,
    },
    {
        "id": "evt014",
        "title": "Corps en Transit — Danse Contemporaine",
        "date": "2026-05-28", "time": "20:30", "end_date": "",
        "location": "L'Octogone", "address": "Prilly-Lausanne",
        "category": "Danse", "subcategory": "Contemporain",
        "description": "La compagnie Alias présente une exploration du corps en mouvement, entre chaos et harmonie.",
        "image": "https://images.unsplash.com/photo-1547153760-18fc86324498?w=800&q=80",
        "price": "CHF 22 / réduit CHF 14", "url": "#",
        "tags": ["danse contemporaine"], "featured": False,
    },
    {
        "id": "evt015",
        "title": "Open Air Cinéma — Plage de Vidy",
        "date": "2026-06-15", "time": "21:30", "end_date": "2026-08-30",
        "location": "Plage de Vidy",
        "address": "Route de Vidy, 1007 Lausanne",
        "category": "Cinéma", "subcategory": "Plein Air",
        "description": "Chaque jeudi soir d'été, projection cinéma au bord du Léman. Transats, pop-corn et coucher de soleil inclus.",
        "image": "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800&q=80",
        "price": "CHF 10", "url": "#",
        "tags": ["cinéma", "lac", "été"], "featured": False,
    },
    {
        "id": "evt016",
        "title": "Lausanne Marathon 2026",
        "date": "2026-10-25", "time": "09:00", "end_date": "",
        "location": "Place de la Navigation", "address": "Ouchy, Lausanne",
        "category": "Sport", "subcategory": "Running",
        "description": "Le marathon le plus spectaculaire de Suisse romande longe les rives du Lac Léman. 42.195 km, semi-marathon et 10 km.",
        "image": "https://images.unsplash.com/photo-1571008887538-b36bb32f4571?w=800&q=80",
        "price": "CHF 80 / semi CHF 50", "url": "#",
        "tags": ["marathon", "lac léman"], "featured": False,
    },
    {
        "id": "evt017",
        "title": "Lausanne à Table — Festival Gastronomique",
        "date": "2026-06-20", "time": "11:00", "end_date": "2026-06-22",
        "location": "Place de la Riponne",
        "address": "Place de la Riponne, 1005 Lausanne",
        "category": "Festival", "subcategory": "Gastronomie",
        "description": "50 chefs lausannois et régionaux investissent la place. Dégustations, masterclasses et marchés de producteurs locaux.",
        "image": "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80",
        "price": "Entrée libre — dégustations dès CHF 5", "url": "#",
        "tags": ["gastronomie", "local"], "featured": False,
    },
    {
        "id": "evt018",
        "title": "MCBA — Figures de l'Abstraction",
        "date": "2026-05-01", "time": "10:00", "end_date": "2026-09-01",
        "location": "Musée Cantonal des Beaux-Arts",
        "address": "Plateforme 10, Place de la Gare 16, 1003 Lausanne",
        "category": "Exposition", "subcategory": "Art moderne",
        "description": "Exploration majeure de l'art abstrait du XXe siècle : Rothko, De Kooning, Kandinsky et artistes suisses méconnus.",
        "image": "https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=800&q=80",
        "price": "CHF 18 / réduit CHF 12", "url": "#",
        "tags": ["abstraction", "rothko"], "featured": True,
    },
    {
        "id": "evt019",
        "title": "Stand-Up Comedy Night",
        "date": "2026-05-30", "time": "20:00", "end_date": "",
        "location": "Les Docks",
        "address": "Avenue du Simplon 34, 1006 Lausanne",
        "category": "Humour", "subcategory": "Stand-up",
        "description": "4 humoristes de la scène française et suisse. Fary, Fadily Camara et deux révélations lausannoises pour 2h de fou-rire.",
        "image": "https://images.unsplash.com/photo-1527224538127-2104bb71c51b?w=800&q=80",
        "price": "CHF 25", "url": "#",
        "tags": ["comedy", "stand-up"], "featured": False,
    },
    {
        "id": "evt020",
        "title": "Pique-nique Musical — Parc de l'Hermitage",
        "date": "2026-06-01", "time": "13:00", "end_date": "",
        "location": "Parc de l'Hermitage",
        "address": "Route du Signal 2, 1010 Lausanne",
        "category": "Famille", "subcategory": "Plein Air",
        "description": "Après-midi musicale en famille dans le parc de l'Hermitage. Concerts folk et animations pour enfants.",
        "image": "https://images.unsplash.com/photo-1530099486328-e021101a494a?w=800&q=80",
        "price": "Gratuit", "url": "#",
        "tags": ["pique-nique", "famille"], "featured": False,
    },
    {
        "id": "evt021",
        "title": "Electronic Music Night — D! Club",
        "date": "2026-05-09", "time": "23:00", "end_date": "",
        "location": "D! Club",
        "address": "Place Centrale 22, 1003 Lausanne",
        "category": "Musique", "subcategory": "Électronique",
        "description": "Nuit électronique avec Solomun (Croatie) et Mathew Jonson (Canada). Système son d'exception.",
        "image": "https://images.unsplash.com/photo-1493676304819-0d7a8d026dcf?w=800&q=80",
        "price": "CHF 30", "url": "#",
        "tags": ["techno", "club"], "featured": False,
    },
    {
        "id": "evt022",
        "title": "Lausanne Urban Art Festival",
        "date": "2026-06-12", "time": "10:00", "end_date": "2026-06-14",
        "location": "Flon & Riponne",
        "address": "Quartier du Flon, Lausanne",
        "category": "Festival", "subcategory": "Street Art",
        "description": "30 artistes internationaux investissent les murs du Flon. Workshops, breakdance battles et expositions éphémères.",
        "image": "https://images.unsplash.com/photo-1567359781514-81212b4047da?w=800&q=80",
        "price": "Gratuit", "url": "#",
        "tags": ["street art", "graffiti"], "featured": False,
    },
    {
        "id": "evt023",
        "title": "Ciné-concert — Metropolis de Fritz Lang",
        "date": "2026-05-17", "time": "20:00", "end_date": "",
        "location": "Salle Métropole",
        "address": "Rue du Maupas 5, 1004 Lausanne",
        "category": "Cinéma", "subcategory": "Ciné-concert",
        "description": "Le chef-d'œuvre de Fritz Lang (1927) en version restaurée 4K avec partition live de l'OCL.",
        "image": "https://images.unsplash.com/photo-1485846234645-a62644f84728?w=800&q=80",
        "price": "CHF 40–65", "url": "#",
        "tags": ["ciné-concert", "fritz lang"], "featured": False,
    },
    {
        "id": "evt024",
        "title": "Marché Artisanal de Printemps",
        "date": "2026-05-03", "time": "10:00", "end_date": "2026-05-04",
        "location": "Place de la Palud",
        "address": "Place de la Palud, 1003 Lausanne",
        "category": "Marché", "subcategory": "Artisanat",
        "description": "80 artisans locaux : céramique, bijoux, textiles, illustrations et gastronomie. Soutien au savoir-faire lausannois.",
        "image": "https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=800&q=80",
        "price": "Entrée libre", "url": "#",
        "tags": ["marché", "artisanat"], "featured": False,
    },
    {
        "id": "evt025",
        "title": "La Traviata — Opéra de Lausanne",
        "date": "2026-05-24", "time": "19:30", "end_date": "",
        "location": "Opéra de Lausanne",
        "address": "Avenue du Théâtre 12, 1005 Lausanne",
        "category": "Musique", "subcategory": "Opéra",
        "description": "Verdi mis en scène par Barrie Kosky. Une relecture audacieuse de l'un des opéras les plus aimés du répertoire.",
        "image": "https://images.unsplash.com/photo-1571019613576-2b22c76fd955?w=800&q=80",
        "price": "CHF 30–130", "url": "#",
        "tags": ["opéra", "verdi"], "featured": False,
    },
]
